language: perl

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

install:
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla Software::License::GPL_2::or_later
  - dzil authordeps --missing | cpanm --quiet --notest
  - dzil listdeps --missing | cpanm --quiet --notest

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov Dist::Zilla::App::Command::cover

script:
  - dzil cover

after_success:
  - test $TRAVIS_PERL_VERSION = '5.22' && cd .build/*/ && cover -report codecov
